### ISSUE TITLE
Work after all nodes have been deleted

### ISSUE THREAD

**Issue by Hatead1** [retejs/task-plugin#12]
Task plugin example on codepen - remove all nodes and press any key.

**Comment by Ni55aN** [comment]
That example needs additional commands to remove unused listeners
For example, add a listeners to `eventHandlers` using `node.id` and remove it on `noderemoved` event

**Comment by Ni55aN** [comment]
That example needs additional commands to remove unused listeners on `noderemoved` event

Updated example: https://codepen.io/Ni55aN/pen/MOYPEz

**Comment by Hatead1** [comment]
Hmm.. I see changes in code, but no changes in result, handlers not clean, alerts shows.

Вопрос вообще немного в другой плоскости: а насколько вообще это правильно? Да, мы можем прибить хендлер, когда удаляем его инициатора (конкретную ноду), но ожидаешь исчезновения ответа на enter при удалении ноды enter, а ничего не исчезает (и понятно почему). Вероятно, нужна какая-то надстройка типа менеджера событий, чтобы отслеживать связи между нодами и рулить событиями (или, например, таймерами).

**Comment by Ni55aN** [comment]
действительно, учитывался только узел для события, поэтому еще раз обновил, чтобы перед каждым перезапуском (engine.process) очищать все подписки на события

**Comment by Hatead1** [comment]
Да, теперь ожидаемое поведение, спасибо.
