### ISSUE TITLE
Using "option" and "output" value for one output

### ISSUE THREAD

**Issue by amirfarzamnia** [retejs/task-plugin#26]

**Comment by Ni55aN** [comment]
> I want socket to have both values of "option" and "output"

Unfortunately it is not supported by v1 (particularly `rete-task-plugin` which is deprecated)

I would recommend migrating to v2, where this plugin has been replaced with `rete-engine` which is more flexible - allows more accuratelу management over dataflow (socket: 'output') and control flow (socket: 'option').
