### ISSUE TITLE
`inputs` is unexpected  when previous component's worker return a promise

### ISSUE THREAD

**Issue by hughfenghen** [retejs/task-plugin#4]
I return a Promise (in AjaxComponent), but receive a simple object (in TextComponent).
[demo](https://codesandbox.io/s/lxoppyol39)

[src/components.js, line: 75]
![image](https://user-images.githubusercontent.com/3307051/48399652-390f1800-e75f-11e8-8728-7ad8a35c3221.png)

After updating the code ([task-plugin code](https://github.com/retejs/task-plugin/blob/master/src/task.js#L35)) to 
```js
    var connections = []
    this.getOutputs().forEach((key) => {
      this.inputs[key].forEach((con) => {
        connections.push({ key, con })
      })
    })

    await Promise.all(connections.map(({ con }) => con && con.run(data, false, garbage, false)))

    connections.forEach(({ key, con }) => {
      if (inputs[key]) {
        inputs[key].push(con.get())
      } else {
        inputs[key] = [con.get()]
      }
    })
```
Result is expected, but I don't know if this modification is appropriate.
Please check it out. Thanks.

**Comment by Ni55aN** [comment]
Is the problem is still actual?

I'm not sure why this happens, but why do you need a Promise? In any case, the request is executed immediately, maybe you should pass the function
